#ifndef GLOBALS_H
#define GLOBALS_H

typedef enum
{
    ERR_NO = 0,
    ERR_OPEN_FILE,
    ERR_ALLOC_MEM,
    ERR_UNEXPECTED_CHAR,
    ERR_UNEXPECTED_TOKEN,
    ERR_UNEXPECTED_EOF,
    ERR_INVALID_SYNTAX,
    ERR_INVALID_TYPE,
    ERR_INVALID_EXPR,
    ERR_INVALID_STMT,
    ERR_INVALID_VAR,
    ERR_INVALID_FUNC,
} errors;

typedef enum
{
    TOKEN_NAME = 1,
    TOKEN_NUMBER,
    TOKEN_FUNC,
    TOKEN_IF,
    TOKEN_OPAREN,
    TOKEN_CPAREN,
    TOKEN_OCURLY,
    TOKEN_CCURLY,
    TOKEN_ASSIGN,
    TOKEN_INT,
    TOKEN_CHAR,
    TOKEN_CHAR_LITERAL,
    TOKEN_PLUS,
    TOKEN_MINUS,
    TOKEN_MUL,
    TOKEN_DIV,
    TOKEN_GREATER,
    TOKEN_LESS,
    TOKEN_EQUAL,
    TOKEN_COMMA,
    TOKEN_EOF
} token_types;

typedef enum
{
    AST_FUNCTION,
    AST_VAR_DECL,
    AST_ASSIGNMENT,
    AST_EXPRESSION,
    AST_IF_STATEMENT,
    AST_FUNC_CALL,
    AST_LITERAL,
    AST_IDENTIFIER
} ast_node_type;

#endif // GLOBALS_H